//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChildcareApplication.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public string BillingStartDate {
            get {
                return ((string)(this["BillingStartDate"]));
            }
            set {
                this["BillingStartDate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public string MaxMonthlyFee {
            get {
                return ((string)(this["MaxMonthlyFee"]));
            }
            set {
                this["MaxMonthlyFee"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("365")]
        public string HoldExpiredRecords {
            get {
                return ((string)(this["HoldExpiredRecords"]));
            }
            set {
                this["HoldExpiredRecords"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public string InfantMaxAge {
            get {
                return ((string)(this["InfantMaxAge"]));
            }
            set {
                this["InfantMaxAge"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8")]
        public string RegularMaxAge {
            get {
                return ((string)(this["RegularMaxAge"]));
            }
            set {
                this["RegularMaxAge"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("04/13/2015 08:00:00")]
        public global::System.DateTime MonOpen {
            get {
                return ((global::System.DateTime)(this["MonOpen"]));
            }
            set {
                this["MonOpen"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("04/13/2015 19:00:00")]
        public global::System.DateTime MonClose {
            get {
                return ((global::System.DateTime)(this["MonClose"]));
            }
            set {
                this["MonClose"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("04/13/2015 08:00:00")]
        public global::System.DateTime TueOpen {
            get {
                return ((global::System.DateTime)(this["TueOpen"]));
            }
            set {
                this["TueOpen"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("04/13/2015 19:00:00")]
        public global::System.DateTime TueClose {
            get {
                return ((global::System.DateTime)(this["TueClose"]));
            }
            set {
                this["TueClose"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("04/13/2015 08:00:00")]
        public global::System.DateTime WedOpen {
            get {
                return ((global::System.DateTime)(this["WedOpen"]));
            }
            set {
                this["WedOpen"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("04/13/2015 19:00:00")]
        public global::System.DateTime WedClose {
            get {
                return ((global::System.DateTime)(this["WedClose"]));
            }
            set {
                this["WedClose"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("04/13/2015 08:00:00")]
        public global::System.DateTime ThuOpen {
            get {
                return ((global::System.DateTime)(this["ThuOpen"]));
            }
            set {
                this["ThuOpen"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("04/13/2015 19:00:00")]
        public global::System.DateTime ThuClose {
            get {
                return ((global::System.DateTime)(this["ThuClose"]));
            }
            set {
                this["ThuClose"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("04/13/2015 08:00:00")]
        public global::System.DateTime FriOpen {
            get {
                return ((global::System.DateTime)(this["FriOpen"]));
            }
            set {
                this["FriOpen"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("04/13/2015 20:00:00")]
        public global::System.DateTime FriClose {
            get {
                return ((global::System.DateTime)(this["FriClose"]));
            }
            set {
                this["FriClose"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("04/13/2015 08:00:00")]
        public global::System.DateTime SatOpen {
            get {
                return ((global::System.DateTime)(this["SatOpen"]));
            }
            set {
                this["SatOpen"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("04/13/2015 12:30:00")]
        public global::System.DateTime SatClose {
            get {
                return ((global::System.DateTime)(this["SatClose"]));
            }
            set {
                this["SatClose"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2015-04-13")]
        public global::System.DateTime SunOpen {
            get {
                return ((global::System.DateTime)(this["SunOpen"]));
            }
            set {
                this["SunOpen"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2015-04-13")]
        public global::System.DateTime SunClose {
            get {
                return ((global::System.DateTime)(this["SunClose"]));
            }
            set {
                this["SunClose"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\\\")]
        public string DefaultSaveFolder {
            get {
                return ((string)(this["DefaultSaveFolder"]));
            }
            set {
                this["DefaultSaveFolder"] = value;
            }
        }
    }
}
